### ISSUE TITLE
Develop Lemmatizer

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#20]
By end of phase two, I need to have developed a lemmatizer.

**Comment by willismonroe** [comment]
https://github.com/cltk/cltk/tree/master/cltk/lemmatize

There isn't a semitic lemmatizer yet (for Hebrew or Arabic) in the CLTK, so we'll have to play with ways of making a lemmatizer work.  I don't necessarily expect this to be finished for the Phase 2 evaluation.

**Comment by adeloucas** [comment]
Cut from the scope; will be revisited later!
