### ISSUE TITLE
Develop Pretty Printing

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#21]
By end of phase two, I need to have developed a pretty printing class.

**Comment by willismonroe** [comment]
- [ ]  Select a text by P-number or siglum
- [ ]  Output selected lines or entire text
- [ ]  Raw text output with line-breaks
- [ ]  Markdown?

**Comment by adeloucas** [comment]
I like this a lot! I adjusted to have raw text come first -- depending on whether or not metadata is to be included will change line numbers; as a user, I think I'd rather have the whole text in front of me prior to making output decisions for Markdown. 

I'll be working on GitHubImport and P-Number output for Pretty Printing at the same time.

**Comment by adeloucas** [comment]
https://github.com/adeloucas/GSoC-Akkadian/blob/e810ab211fe6e6a569e8f23cabc8e1fd7db8d57d/Importer/cdli_corpus.py#L159-L191

Looking a bit better! Not sure how to tackle action item three, namely selecting lines within the text. I think I know how to work this out, but I'm not sure what the end result should look like. For Markdown, should this be after ATFConverter is used on a text?
