### ISSUE TITLE
Develop CDLI Import Corpus class

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#22]
By end of phase two, I need to have developed a CDLI Import corpus class.

**Comment by willismonroe** [comment]
Source data: https://github.com/cdli-gh/data

How to add a corpus to the CLTK: https://github.com/cltk/cltk/wiki/How-to-add-a-corpus-to-the-CLTK

**Comment by adeloucas** [comment]
https://github.com/adeloucas/cltk/commit/6391ccb4d8dda75055a1381161855ef9e8fbb569

https://github.com/adeloucas/cltk/commit/d48676bc4fd72330b3dd5a607e61663f944c8a55

I am able to import the corpus in a virtual environment, but "nothing" downloads:

![image](https://user-images.githubusercontent.com/38022737/41566529-c04ef07e-7310-11e8-87c4-54f5565b4853.png)

**Comment by adeloucas** [comment]
I'm a dummy. It worked. I was looking in the wrong folder. On to pull request!

**Comment by willismonroe** [comment]
I'm thinking that this code should be moved to a separate folder.  It's no longer really an ATFConverter, it just so happens that the CDLI data is *in* ATF.

Also, could you write out a spec for this code.  What is it intended to do, what are its inputs, how will other classes make use of it.  Imagine a workflow that involves this code, where does it fit?

**Comment by adeloucas** [comment]
Made structural changes and will upload this all to "development" (accidentally already merged earlier today...). 

I'll work on the spec tonight and upload it later tonight and tomorrow.

**Comment by adeloucas** [comment]
Right now, I have a functionary description of this code (https://github.com/adeloucas/GSoC-Akkadian/blob/cdli_import_development/README.md#program-specification) that may be missing the mark; let me know if it is.

Would it be beneficial to additionally make graphics or otherwise write a tutorial of going through the classes and methods?
