### ISSUE TITLE
Familiarize myself with OS

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#26]
I should familiarize myself with OS, especially for Importing CDLI Corpus.

**Comment by adeloucas** [comment]
#28 
@willismonroe :
This is a good example of relative vs. absolute paths. A perfect time to learn the intracacies of the os module.

Try loading up a python REPL in the root directory of your project and figuring out how to find files and join paths. Add an os call in the test to have it print out what directory it's currently working in (there's an os method for that!).

**Comment by willismonroe** [comment]
Also useful: https://realpython.com/python-pathlib/
