### ISSUE TITLE
Break up list comprehension for underline_remover and sumerian_converter

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#27]
Currently there is a list comprehension inside a list comprehension. It can be made more neatly via being passed through.

**Comment by willismonroe** [comment]
https://github.com/adeloucas/GSoC-Akkadian/blob/master/ATFConverter/atf_converter.py#L275

**Comment by adeloucas** [comment]
Viable solution?

https://github.com/adeloucas/GSoC-Akkadian/blob/pretty_print_development/ATFConverter/pretty_print.py#L51-L58

https://github.com/adeloucas/GSoC-Akkadian/blob/pretty_print_development/ATFConverter/pretty_print.py#L86-L93
