### ISSUE TITLE
os.path.join receiving errno. 2

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#28]
`file = os.path.join('texts', 'Akkadian.txt')` is sending back Errno. 2:

***

F
token_test.py:35 (Test1.test_line_tokenizer)
self = <token_test.Test1 testMethod=test_line_tokenizer>

    def test_line_tokenizer(self):
        """
            Tests line_tokenizer.
            """
        file = os.path.join('texts', 'Akkadian.txt')    # broken - errno 2...
        # file = \
        #     r"C:\\Users\\andrew.deloucas\\GSoC-Akkadian\\texts\\Akkadian.txt"
>       output = TOKENIZER.line_tokenizer(file)

token_test.py:43: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ATFConverter.tokenizer.Tokenizer object at 0x000002565243AF98>
text = 'texts\\Akkadian.txt'

    def line_tokenizer(self, text):
        """
            From a .txt file, outputs lines as string in list.
    
            input:  21. u2-wa-a-ru at-ta e2-kal2-la-ka _e2_-ka wu-e-er
                    22. ... u2-ul szi-...
                    23. ... x ...
            output:['21. u2-wa-a-ru at-ta e2-kal2-la-ka _e2_-ka wu-e-er',
                    '22. ... u2-ul szi-...',
                    '23. ... x ...',]
    
            :param: .txt file containing untokenized string
            :return: lines as strings in list
            """
        line_output = []
    
>       with open(text, mode='r+', encoding='utf8') as file:
E       FileNotFoundError: [Errno 2] No such file or directory: 'texts\\Akkadian.txt'

..\ATFConverter\tokenizer.py:92: FileNotFoundError

**Comment by willismonroe** [comment]
This is a good example of relative vs. absolute paths.  A perfect time to learn the intracacies of the `os` module.

Try loading up a python REPL in the root directory of your project and figuring out how to find files and join paths.  Add an os call in the test to have it print out what directory it's currently working in (there's an os method for that!).

**Comment by adeloucas** [comment]
Solved with:
`file = os.path.join('..', 'texts', 'Akkadian.txt')`

Will continue to look into this suggestion for the sake of learning the os module. I'll copy and paste this comment into that issue and close this one.
