### ISSUE TITLE
Set up and clean up branches

### ISSUE THREAD

**Issue by willismonroe** [adeloucas/GSoC-Akkadian#29]
Projects generally follow a feature -> development -> main/release structure.

This is a good article on general structure, a bit overly complex for what you're doing but still a good read: https://nvie.com/posts/a-successful-git-branching-model/

![image](https://user-images.githubusercontent.com/715210/41502505-57849310-7170-11e8-99aa-4c1a6dc830a6.png)

**Comment by adeloucas** [comment]
Current system (let me know if I need to make adjustments):
Work on each feature separately (pretty_print, cdli_import) and upload to Development branch when significant improvements are made. After review and acceptance of feature's improvements, pull from development to refresh features if need be.

This link was helpful for understanding this process, thank you!

**Comment by TylerKirby** [comment]
Having too many feature branches will lead to more merge conflicts in the future. Try to limit yourself to only one feature branch at a time. I think you have several open at the moment.

**Comment by adeloucas** [comment]
Done! Current branches: Master, Development, CDLI Import Development, Willis. Closed down Pretty Print and Lemmatizer. Intend to Re-open Pretty Print once CDLI Import is ready to merge.

**Comment by adeloucas** [comment]
Closing for the sake of cleaning up github. I understand this a lot more now!
