### ISSUE TITLE
Capturing key with pnumbers without ampersand 

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#35]
In ARM1, text 115 does not contain our '&' sign in its pnumber, causing 'discern_texts' to fail and effectively skip a key (i.e. text_contents has ARM1 116 pull up ARM115's text).

**Comment by willismonroe** [comment]
This might be an argument for a regex solution.

In general it's best to use the standard pythonic tools to their best ability and least impact as far as they will take you, and then fall back on a more complex solution.  It should be simple to code up a regex that matches &P{digits} or P{digits} at the start of a line.

**Comment by adeloucas** [comment]
Solved!
