### ISSUE TITLE
Rework file handling

### ISSUE THREAD

**Issue by willismonroe** [adeloucas/GSoC-Akkadian#39]
Generally the keyword `file` is avoided when writing Python code because it is also the name of the type of object returned by the `open()` function.  Convention is to use just the letter `f` as a shorthand for the temporarily open file.

Related to that, the process of opening and reading from files is best situated inside of a context:
```
with open('filename.txt') as f:
    data = f.read()
```
This only opens the file as long as the code within the context block needs to run and then automatically closes the file, rather than having to manually call `f.close()` later on.

Here's the relevant explanation from the Python tutorial: https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

**Comment by willismonroe** [comment]
I realize that your code in FileImport uses contexts...

**Comment by adeloucas** [comment]
No worries! I have changed any instances where "file" could be misconstrued (changed to either 'f' or 'text_file' 0).
