### ISSUE TITLE
Avoid repeated opening of files

### ISSUE THREAD

**Issue by willismonroe** [adeloucas/GSoC-Akkadian#40]
Your [CDLIImport](https://github.com/adeloucas/GSoC-Akkadian/blob/cdli_import_development/Importer/cdli_import.py#L24) class contains this general scheme twice:
```
        output = []
        f_i = FileImport()
        file = os.path.join('..', 'texts', 'cdli_corpus.txt')
        text = f_i.read_file(file)
        contents = False
        for line in text:
            if line.rstrip().startswith(pnumber):
                contents = True
            elif len(line) == 0:
                contents = False
            if contents:
                output.append(line)
        return output
```

The variable text here could be contained within the class and read at an earlier point and then referred to.

For instance, you could initialize the class object with a filename, then call `.read_file()` (a class method) to ingest the file.  This function would read the file and store its contents in a class variable `self.text` (or something) which all future methods could then use.

**Comment by adeloucas** [comment]
Tentatively understood... how I interpreted this change: 

1) add self.text = FileImport().read_file to __init__
2) Deleted lines 2, 4
3) Lines now read: 

`output = []`
`f = os.path.join('..', 'texts', read_file)` for __file_pull__
`f = os.path.join('..', 'texts', 'cdli_corpus.txt'))` for __import_text__
`text = self.text(f)`

I don't think that my edit is entirely correct because I don't think these contents are being stored in self.text. Could you help with that logic?

**Comment by willismonroe** [comment]
The `__init__` function should take a filename argument which would be assigned to `self.filename`.  A `.read_file()` function would then read the contents of the file and maybe store the entire file as a string in `self.raw_file` and the lines in `self.lines`.  That's basically it for now as far as the FileImporter is concerned.

Think of it from an architecture standpoint, what is specific to the file as a piece of data on the computer versus what is specific to a corpus as a way of cataloging texts.  Whatever is specific to how a file exists on a computer (text file, xml file, from the web, on the hard drive etc...) goes in FileImporter, whatever is specific to the data coming out of the file post reading can go in CorpusImporter... i.e. how the texts are enumerated in the file, how the metadata is formatted etc...

**Comment by TylerKirby** [comment]
Seconding Willis comment here. Initiating the same resources multiple times in a Python program is the number one reason for their performance slow down.

**Comment by adeloucas** [comment]
Current difficulty:

As it stands, `self.file_lines` words in line 2 (FileImport.read_file(self)) works, but not when defined in read_file. The commented-out lines are there for sake of showing what I've written to try and work; in read_file, I've also tried the configuration at the bottom to no avail.

`def __init__(self, filename):`
        `self.filename = filename`
        `self.file_lines = FileImport.read_file(self)    
        `self.texts = FileImport.__discern_texts__(self)`
       `#self.raw_file = None`
        `#self.file_lines = None`

    def read_file(self):
       line_output = []
       with open(self.filename, mode='r+', encoding='utf8') as f:
            #self.raw_file = f.read()
            for line in f:
                line_output.append(line.rstrip())
                #self.file_lines = self.raw_file.splitlines()
            return line_output

***


    def read_file(self):
       with open(self.filename) as f:
            self.raw_file = f.read()
       self.file_lines = self.raw_file.splitlines()

**Comment by willismonroe** [comment]
When you define class methods you need to include `self` in the method's
arguments if the method needs to access properties of the instance.  I.e.
if `.read_file` needs to access `self.filename` then it has to be defined
as `def read_file(self):`

When you call those methods you do not need to put `self` in the method
call.  i.e. if you want to call `.read_file` later it only needs to be
`.read_file()`.
