### ISSUE TITLE
Split logic of file reading and corpus ingesting between FileImporter and CDLIImporter

### ISSUE THREAD

**Issue by willismonroe** [adeloucas/GSoC-Akkadian#41]
I've been trying to think of a larger way to split up the logic between these two classes.

FileImporter should manage the copying, movement, storage, and reading of files both from the web and on the harddisk of the user.  It could present a number of functions that list out the available corpus files to read, reads individual corpus files, updates corpus files based on urls etc...

CDLIImporter (or maybe just CorpusImporter) would then take a file read by FileImporter and "understand" the contents.  This includes dividing a raw file into individual texts, outputting a TOC for the corpus, and passing off lines of raw text to the tokenizer and lemmatizer.  This might involve folding the line tokenizer (`.splitlines()` is enough) into the class.

Think about how the CorpusImporter class could represent a corpus as a Python data structure.  What would be the important parts of the overall structure, what would each text look like if described by a Python dictionary.  You've got all the tools now to turn the CDLI corpus file into a rather feature rich accessible Python dictionary.  Keys as Pnums?  Bibliography list with room for future additions?  List of metadata?  Lines of text with or without initial numbers?  There are lots of pieces of data to encode, and the nice thing is you can slowly build up more features if you start from a very stable and simple initial structure.

**Comment by willismonroe** [comment]
Here's some very rough sketching I did a few days ago around some potential ideas behind the CorpusImporter class:
```
class CDLIText:
    """
    A data structure representing a text object
    """

    def __init__(self, pnum, edition):
        self.pnum = pnum
        self.edition = edition
        self.text_lines = []

    @classmethod
    def from_lines(cls, lines):
        try:
            header = [line for line in lines if line.startswith(
                '&P')][0].split('=')
            if len(header) > 1:
                pnum = header[0].rstrip()
                edition = header[1].lstrip()
            else:
                pnum = header[0].rstrip()

            return cls(pnum, edition)
        except IndexError:
            print("No header information in text: {}".format(lines))



class CorpusImporter:

    def __init__(self, filename):
        self.filename = filename
        self.texts = []

    def parse_file(self):
        """Reads in the file specified by self.filename and outputs
        a list of CDLIText objects to self.text.
        """

        with open(self.filename) as f:
            self.raw_file = f.read()

        texts, text = [], []
        for line in self.raw_file.splitlines():
            if line.strip() == '':
                if len(text) > 0:
                    texts.append(text)
                text = []
            else:
                text.append(line)
        texts.append(text)

        for text in texts:
            self.texts.append(CDLIText.from_lines(text))

    def corpus_length(self):
        """This function checks if the file has already been parsed
        in which case it just returns the length of self.texts.  Otherwise
        it loads up the file and counts instances of '&P'.

        Returns:
            Int -- Length of corpus in number of texts
        """

        if len(self.texts) > 0:
            return len(self.texts)
        else:
            return len(
                [line for line in open(self.filename).readlines()
                 if line.startswith('&P')])

    def get_pnums(self):
        return [text.pnum for text in self.texts]

    def print_bibliography(self):
        for text in self.texts:
            print(f"{text.pnum}: {text.edition}")
```

I also added a CDLIText class as well, that way the CorpusImporter could import different types of corpora and turn each text into the appropriate text class, which itself would have custom features for a type of text.

**Comment by willismonroe** [comment]
The `@classmethod` in `CDLIText` is a factory method, meaning you can use it to make new `CDLIText` objects.  Rather than have to parse the text itself you can make a method in the text class that knows what to do with the text, parse everything and return a new object with the appropriate variables populated.

**Comment by adeloucas** [comment]
I'll work on sculpting this for today:
file_importer (read_file, import_text, _update_text_), and 
file_reader (discern_texts, split_texts, table_of_contents, text_call_names, text_contents, text_print, line_tokenizer).

I'll work with your draft and notes above as well to restructure these files.
