### ISSUE TITLE
Dependency build file

### ISSUE THREAD

**Issue by TylerKirby** [adeloucas/GSoC-Akkadian#53]
Since your code makes use of third libraries, you need to include some build configuration.

In Python, you have two options:
1) add all the libs you're using to `requirements.txt`. I would also recommend using a virtual env for local development (https://docs.python-guide.org/dev/virtualenvs/)
2) create a pipfile and use pipenv (https://docs.pipenv.org/). This is the build method officially recommended by the Python Software Foundation (the core devs of Python): https://packaging.python.org/tutorials/managing-dependencies/

Here's the cltk dependency file for reference: https://github.com/cltk/cltk/blob/master/requirements.txt. Note that the cltk does not use pipenv.

**Comment by adeloucas** [comment]
After clean up, I only am using `os` and `re`; do I need to still add them to the text file?

**Comment by TylerKirby** [comment]
Nope! If you end up using anything other than core modules though be sure to add them to a `requirements.txt`.
