### ISSUE TITLE
Prepare cltk pull request

### ISSUE THREAD

**Issue by TylerKirby** [adeloucas/GSoC-Akkadian#55]
The program is almost over so we need to identify what code we want to include in the cltk. @adeloucas you'll need to fork the cltk and place your code in the appropriate place.

**Comment by adeloucas** [comment]
My initial proposal: 

https://github.com/adeloucas/cltk/commit/db621d1cce2b481b5d581a05b0b7bceb2b55ac52

**Comment by adeloucas** [comment]
Oh yeah! Forgot the tests :( I'll add when I address the comments!

for Pylint, nothing is below an 9! The weakest ones are atf_converter at 9.15 and pretty_print at a 9.03.

**Comment by willismonroe** [comment]
It looks good, your documentation is very thorough which is good!  I had two minor comments.

Also have you tested the FileReader/CorpusImporter on the entire cdli corpus yet?

**Comment by adeloucas** [comment]
Ah! Just saw this -- I haven't... I'll do this tonight and see what results I get.

**Comment by adeloucas** [comment]
three commits:
1) Main one with major changes https://github.com/adeloucas/cltk/commit/417ee9a0f85504cf95f0b6ee948df8c0296f0465
2) One where I fixed all the find-and-replaces that pycharm goofed up (texts -> Akkadian test texts) https://github.com/adeloucas/cltk/commit/1f421145c443b7f1860735721707c7c326ac02ba
3) brushing up small fixes https://github.com/adeloucas/cltk/commit/a7c256379f7a048ce6c74e872484be6b9b205e41

**Comment by adeloucas** [comment]
@willismonroe -- I see that `find_transliteration` doesn't work! Makes sense because cdli_corpus doesn't contain any metadata.

I'll try to tackle this bug today.

**Comment by adeloucas** [comment]
https://github.com/adeloucas/cltk/commit/0a88c02e6b6cdd2337a1a7fa6fae387c08f59027

**Comment by TylerKirby** [comment]
This looks good to me
