### ISSUE TITLE
`cdli_corpus` doesn't 'find' everything

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#57]
in searching through the `table_of_contents`, pulled from cdli_corpus, not every text is found.

![image](https://user-images.githubusercontent.com/38022737/43351528-45bcee20-91c8-11e8-8703-1f7af6b346c4.png)
![image](https://user-images.githubusercontent.com/38022737/43351531-560a5c9a-91c8-11e8-9f0e-c5e57892c08d.png)

**Comment by adeloucas** [comment]
Currently:

```
cc = CDLICorpus()
chunk = cc._chunk_text(fi.file_lines)
pnum = cc._find_cdli_number(fi.file_lines)
edition = cc._find_edition(fi.file_lines)
print(len(chunk))
print(len(pnum))
print(len(edition))
```
Output is: 
111350 (chunk text)
116643 (cdli)
116643 (edition)

I suspect that this is due to instances where there are no breaks in a text, e.g.:

![image](https://user-images.githubusercontent.com/38022737/43431567-3f16b12a-9423-11e8-808f-782a5b8c8082.png)

Proposal:

Change chunk text to work with a .startswith() solution rather than by empty line... We'll see!

**Comment by willismonroe** [comment]
Yeah currently `_chunk_texts` just looks for empty lines... try switching
it to look for Pnums (with or without &'s)

**Comment by adeloucas** [comment]
If I get it to work for pnums, it'll work for the corpus, but not with texts that contain metadata, where there is a pnum in it. I'm trying to write around this, but not finding any solution. I know why this code doesn't work, but I don't know how to work around it. Some guidance is needed! 

https://github.com/adeloucas/GSoC-Akkadian/blob/30a4a9170538e61b2ce848c96b64e8ddf3034c36/Importer/cdli_corpus.py#L43-L63

**Comment by willismonroe** [comment]
Why not split the text on pnums and then look for metadata later...

If you split the entire corpus on pnums you'll get chunks of text with or
without metadata but each will be distinct texts.  The find_metadata tool
can then look in each one and see if there's any metadata to discover, if
not it can leave metadata blank.

**Comment by adeloucas** [comment]
Chunk_test cuts into the text like so: 

![comp failure](https://user-images.githubusercontent.com/38022737/43560293-9fd96f8a-95c6-11e8-9cab-5f346937ee8b.png)

re.match is splitting on the line entirely, which I'm not sure how to stop (parentheses don't seem to fix this issue). 

Walking through the two different data for my own sake:
1) Metadata (starts with 'Primary Publication:', ends with 'Transliteration'; contains pnum w/o &)
2) No Metadata (starts with pnum, ~99% of the time with a &, but not always).

I want to group data accurately, regardless of metadata. Does this mean I should consider the two scenarios, or am I missing the larger point?

**Comment by adeloucas** [comment]
This works for everywhere except for when we have texts "stuck" together (see attached photo). I looked back at the find_transliteration, and it's cutting out `transliteration:`, which is fine, but in cases where a text goes from the last line into the pnum of another text, I don't know how how split the text. 

I can figure how to keep the delimiter if this case were a string, but for line-by-line cases, I'm not sure how to tackle this. I want to try and write a previous / next line reader (e.g. `if previous line != 'transliteration:' and next(line.startswith(#atf))` or something like this), but I don't know if I'm trying to use a wrench to pull out a splinter. (e.g. of what I'm thinking... https://stackoverflow.com/questions/22824743/read-next-and-previous-lines-while-reading-file-line-by-line?rq=1)

![image](https://user-images.githubusercontent.com/38022737/43562117-742f8b86-95cf-11e8-9f31-20ee161de427.png)

**Comment by adeloucas** [comment]
The of this is to incorporate into ingest, making sure that any "stuck" texts are separated. There are still some edge case(s), but this is closest yet!

https://github.com/adeloucas/GSoC-Akkadian/blob/86165154e1fc33f3dfa85cbdb136e10daaf0e95b/Importer/cdli_corpus.py#L43-L53

![indexing](https://user-images.githubusercontent.com/38022737/43680589-e1a4f74e-97f2-11e8-8fb8-63240a393137.png)
![with reverse sorted](https://user-images.githubusercontent.com/38022737/43680590-e6d30c6a-97f2-11e8-9c8f-8d162ff63939.png)

**Comment by willismonroe** [comment]
I don't like the idea of inserting spaces before Pnums we should be able to parse the file as is... otherwise we're introducing more complexity that we'll have to maintain in the future if the file format changes.

Here's a snippet that seems to work pretty well:

```
texts, text = [], []
for line in lines:
    if re.match('\&?P\d{6}', line):
        if len(text) > 0:
            texts.append(text)
        text = [line]
    else:
        text.append(line)
texts.append(text)
```

That produces 116643 texts for me.

**Comment by willismonroe** [comment]
Right, yeah.  That text is in the cdli_corpus.txt file though and the method above does find it there since the chunk starts with the Pnum.  Where is your ARM1 file coming from again?

**Comment by adeloucas** [comment]
When you download a singular text or otherwise through a search function (e.g. [ARM1](https://cdli.ucla.edu/search/search_results.php?PrimaryPublication=ARM+01)), it'll give the data. Got it fixed through this (will push shortly):

```
texts, text = [], []
        if re.match('Primary publication:', file_lines[0]):
            for line in file_lines:
                if line.strip() == '':
                    if len(text) > 0:   # pylint: disable =len-as-condition
                        texts.append(text)
                    text = []
                else:
                    text.append(line.rstrip())
            texts.append(text)
        else:
            for line in file_lines:
                if re.match('&?P\d{6}', line):
                    if len(text) > 0:
                        texts.append(text)
                    text = [line]
                else:
                    text.append(line)
            texts.append(text)
        return texts
```

**Comment by willismonroe** [comment]
Ah ok, that makes sense.  Yeah the corpus importer should handle both cases.

Btw we should use the transcription data!  Aligning that with the
transliteration would give us a handy lookup table for normalizations.
