### ISSUE TITLE
file_catalog is broken

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#59]
https://github.com/adeloucas/GSoC-Akkadian/blob/3d8ee43eff8de4384408bc79d02a75d5b93f48c9/Importer/file_importer.py#L43-L49

Changed to: 

```
   def file_catalog(self):
        """
        Looks at the folder filename is in and lists other files in the folder.
        :return: list of files.
        """
        ex = os.path.split(self.filename)
        f_c = os.listdir(ex[0])
```

Debugging, this works:

![image](https://user-images.githubusercontent.com/38022737/43369353-92b59f38-9321-11e8-8eda-862de01c6737.png)

However, it never translates into the actual test (l.45). If I use this exact code in the test, it works (l. 46-47):

![image](https://user-images.githubusercontent.com/38022737/43369098-b37cd52e-931c-11e8-96d8-8c9bcd1485d5.png)

**Comment by willismonroe** [comment]
My first thought is whether or not you're sorting the lists of files...
Maybe sort both and then compare?

**Comment by adeloucas** [comment]
That did it! Solution:

```
pathway = os.path.split(self.filename)
self.catalog= sorted(os.listdir(pathway[0]))
```

**Comment by willismonroe** [comment]
Make sure you sort both, even it passes now, just in case if something
changes in the future, you know both are sorted according to the same
system.
