### ISSUE TITLE
_ingest doesn't work for `only_normalization=True`

### ISSUE THREAD

**Issue by adeloucas** [adeloucas/GSoC-Akkadian#64]
_ingest works if `only_normalization=False`

When `only_normalization=True`, the following can be discerned:

```
cdli_corpus._chunk_text(file_import.file_lines, only_normalization=True)
len(c._find_edition(f.file_lines))
len(c._find_cdli_number(f.file_lines))
len(c._find_metadata(f.file_lines))
len(c._find_edition(f.file_lines))
```
All these guys return 74, which is correct and great. You can even find texts this way:

`print(c._chunk_text(f.file_lines, only_normalization=True)[2])` (returns ARM 01, 001, in my case)

However, upon _ingesting this, we receive this:
```
c._ingest(c._chunk_text(f.file_lines, only_normalization=True)[2]))
None
```
What this means is that _ingest is not taking any particular _chunk_text, which is causing `ingest_text_file` to return empty. Further proof -- c.texts returns the correct AMOUNT of texts, but the actual application of text into edition / cdli number is empty. Attempted to add `only_normalization=True` to the self. uses in the `_find` methods, and it works fine with and without this normalization added.

**Comment by adeloucas** [comment]
Debugging... it appears that ingest will accept a text just fine, but `self._find` functions aren't working. 

So, proposed question: why does this work for non-normalized texts, but not normalized texts?

![ingest](https://user-images.githubusercontent.com/38022737/43875104-29fa01f2-9b44-11e8-8f06-f92796d24f51.png)

**Comment by willismonroe** [comment]
This means the output of `_chunk_text` looks like this:
```
[['&P464358 = RIME 4.03.06.add21 (Codex Hammurapi) composite',
  '#tr.ts: īnu anum ṣīrum',
  '#tr.ts: šar anunnakī',
  '#tr.ts: enlil',
  '#tr.ts: bēl šamê',
```

That may be fine and something we can clean up after the fact.
